require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

module Guara
  describe ActiveCrm::ScheculedsController do
  
    # This should return the minimal set of attributes required to create a valid
    # ActiveCrm::Scheculed. As you add validations to ActiveCrm::Scheculed, be sure to
    # update the return value of this method accordingly.
    def valid_attributes
      { "subject" => "MyString" }
    end
  
    # This should return the minimal set of values that should be in the session
    # in order to pass any filters (e.g. authentication) defined in
    # ActiveCrm::ScheculedsController. Be sure to keep this updated too.
    def valid_session
      {}
    end
  
    describe "GET index" do
      it "assigns all active_crm_scheculeds as @active_crm_scheculeds" do
        scheculed = ActiveCrm::Scheculed.create! valid_attributes
        get :index, {}, valid_session
        assigns(:active_crm_scheculeds).should eq([scheculed])
      end
    end
  
    describe "GET show" do
      it "assigns the requested active_crm_scheculed as @active_crm_scheculed" do
        scheculed = ActiveCrm::Scheculed.create! valid_attributes
        get :show, {:id => scheculed.to_param}, valid_session
        assigns(:active_crm_scheculed).should eq(scheculed)
      end
    end
  
    describe "GET new" do
      it "assigns a new active_crm_scheculed as @active_crm_scheculed" do
        get :new, {}, valid_session
        assigns(:active_crm_scheculed).should be_a_new(ActiveCrm::Scheculed)
      end
    end
  
    describe "GET edit" do
      it "assigns the requested active_crm_scheculed as @active_crm_scheculed" do
        scheculed = ActiveCrm::Scheculed.create! valid_attributes
        get :edit, {:id => scheculed.to_param}, valid_session
        assigns(:active_crm_scheculed).should eq(scheculed)
      end
    end
  
    describe "POST create" do
      describe "with valid params" do
        it "creates a new ActiveCrm::Scheculed" do
          expect {
            post :create, {:active_crm_scheculed => valid_attributes}, valid_session
          }.to change(ActiveCrm::Scheculed, :count).by(1)
        end
  
        it "assigns a newly created active_crm_scheculed as @active_crm_scheculed" do
          post :create, {:active_crm_scheculed => valid_attributes}, valid_session
          assigns(:active_crm_scheculed).should be_a(ActiveCrm::Scheculed)
          assigns(:active_crm_scheculed).should be_persisted
        end
  
        it "redirects to the created active_crm_scheculed" do
          post :create, {:active_crm_scheculed => valid_attributes}, valid_session
          response.should redirect_to(ActiveCrm::Scheculed.last)
        end
      end
  
      describe "with invalid params" do
        it "assigns a newly created but unsaved active_crm_scheculed as @active_crm_scheculed" do
          # Trigger the behavior that occurs when invalid params are submitted
          ActiveCrm::Scheculed.any_instance.stub(:save).and_return(false)
          post :create, {:active_crm_scheculed => { "subject" => "invalid value" }}, valid_session
          assigns(:active_crm_scheculed).should be_a_new(ActiveCrm::Scheculed)
        end
  
        it "re-renders the 'new' template" do
          # Trigger the behavior that occurs when invalid params are submitted
          ActiveCrm::Scheculed.any_instance.stub(:save).and_return(false)
          post :create, {:active_crm_scheculed => { "subject" => "invalid value" }}, valid_session
          response.should render_template("new")
        end
      end
    end
  
    describe "PUT update" do
      describe "with valid params" do
        it "updates the requested active_crm_scheculed" do
          scheculed = ActiveCrm::Scheculed.create! valid_attributes
          # Assuming there are no other active_crm_scheculeds in the database, this
          # specifies that the ActiveCrm::Scheculed created on the previous line
          # receives the :update_attributes message with whatever params are
          # submitted in the request.
          ActiveCrm::Scheculed.any_instance.should_receive(:update_attributes).with({ "subject" => "MyString" })
          put :update, {:id => scheculed.to_param, :active_crm_scheculed => { "subject" => "MyString" }}, valid_session
        end
  
        it "assigns the requested active_crm_scheculed as @active_crm_scheculed" do
          scheculed = ActiveCrm::Scheculed.create! valid_attributes
          put :update, {:id => scheculed.to_param, :active_crm_scheculed => valid_attributes}, valid_session
          assigns(:active_crm_scheculed).should eq(scheculed)
        end
  
        it "redirects to the active_crm_scheculed" do
          scheculed = ActiveCrm::Scheculed.create! valid_attributes
          put :update, {:id => scheculed.to_param, :active_crm_scheculed => valid_attributes}, valid_session
          response.should redirect_to(scheculed)
        end
      end
  
      describe "with invalid params" do
        it "assigns the active_crm_scheculed as @active_crm_scheculed" do
          scheculed = ActiveCrm::Scheculed.create! valid_attributes
          # Trigger the behavior that occurs when invalid params are submitted
          ActiveCrm::Scheculed.any_instance.stub(:save).and_return(false)
          put :update, {:id => scheculed.to_param, :active_crm_scheculed => { "subject" => "invalid value" }}, valid_session
          assigns(:active_crm_scheculed).should eq(scheculed)
        end
  
        it "re-renders the 'edit' template" do
          scheculed = ActiveCrm::Scheculed.create! valid_attributes
          # Trigger the behavior that occurs when invalid params are submitted
          ActiveCrm::Scheculed.any_instance.stub(:save).and_return(false)
          put :update, {:id => scheculed.to_param, :active_crm_scheculed => { "subject" => "invalid value" }}, valid_session
          response.should render_template("edit")
        end
      end
    end
  
    describe "DELETE destroy" do
      it "destroys the requested active_crm_scheculed" do
        scheculed = ActiveCrm::Scheculed.create! valid_attributes
        expect {
          delete :destroy, {:id => scheculed.to_param}, valid_session
        }.to change(ActiveCrm::Scheculed, :count).by(-1)
      end
  
      it "redirects to the active_crm_scheculeds list" do
        scheculed = ActiveCrm::Scheculed.create! valid_attributes
        delete :destroy, {:id => scheculed.to_param}, valid_session
        response.should redirect_to(active_crm_scheculeds_url)
      end
    end
  
  end
end
