source 'https://rubygems.org'

eval(File.read(File.dirname(__FILE__) + '/../common_dependencies.rb'))


gemspec
	
group :assets do
  gem 'uglifier', '1.2.3'
  gem "jquery-rails"
end

group :production do
	if ENV["SERVER"]
    gem 'thin', '1.5'
  end
end

group :development do
  gem 'annotate', '~> 2.4.1.beta'
  gem 'nested_scaffold'
  unless ENV["CI"]
	  gem 'ruby-debug19'	
	  gem 'linecache19'
  end
end

group :test do
  #MAC OS Especific
  gem 'rb-fsevent', '0.9.1', :require => false
  gem 'growl', '1.0.3', :require => false
  gem 'faker'

  #Cucumber
  gem 'cucumber-rails', '1.2.1', :require => false
end

