source 'https://rubygems.org'

eval(File.read(File.dirname(__FILE__) + '/../common_dependencies.rb'))


# view
gem 'bootstrap-sass', '~> 2.3.0.0'
gem 'bootstrap-will_paginate', '0.0.6'

# Forms
gem 'will_paginate', '3.0.3'
gem 'rails3-jquery-autocomplete'

#test support
gem 'faker', '1.0.1'

#login rules
gem 'devise'
gem 'cancan', '~> 1.6.8'

#model
gem "meta_search"
gem 'activeadmin', '0.5.0'

#criptar
gem 'bcrypt-ruby', '3.0.1'

#BR
gem 'brazilian-rails'
gem 'rails-i18n'

#converters
gem 'spreadsheet'
gem 'ruby-rtf', '0.0.1'

#extends
gem 'active_extend', :path => '../../active_extend/'
	
group :assets do
  gem 'uglifier', '1.2.3'
end

group :production do
	if ENV["SERVER"]
    gem 'thin', '1.5'
  end
end

group :development do
  gem 'annotate', '~> 2.4.1.beta'
  gem 'nested_scaffold'
  unless ENV["CI"]
	  gem 'ruby-debug19'	
	  gem 'linecache19'
  end
end

group :test do
  #MAC OS Especific
  gem 'rb-fsevent', '0.9.1', :require => false
  gem 'growl', '1.0.3', :require => false

  #Cucumber
  gem 'cucumber-rails', '1.2.1', :require => false
end