
eval(File.read(File.dirname(__FILE__) + '/../common_dependencies.rb'))

gem 'guara_core', :path => "../core/"
gem 'guara_crm', :path => "../crm/"

gem "paperclip", "~> 2.7"

gem "mail"

gem 'bootstrap-wysihtml5-rails'

gem 'wicked_pdf'
gem "wkhtmltopdf-binary"


gemspec
