development:
  adapter: postgresql
  database: guara_dev
  username: postgres
  password: 
  host: localhost
  encoding: UTF8
  pool: 45
  timeout: 5000

test:
    adapter: postgresql
    database: guara_test
    username: postgres
    password: 
    host: localhost
    encoding: UTF8
    pool: 45
    timeout: 5000

production:
    adapter: postgresql
    prepared_statements: false
    database: guara_prod
    username: postgres
    password: 
    host: localhost
    encoding: UTF8
    pool: 45
    timeout: 5000
