eval(File.read(File.dirname(__FILE__) + '/../common_dependencies.rb'))

gem 'guara_core', :path => "../../guara/core"
gem 'guara_crm', :path => "../../guara/crm"

group :assets do
  gem 'jquery-ui-rails'
end

gemspec
